ch1 = read.table("challenge1.txt")
ch1 <- rbind(ch1, rep(1, 50))
ch2 = read.table("challenge2.txt")
ch2 <- rbind(ch2, rep(2, 50))
ch1 <- cbind(ch1, ch2)
ch1 <- t(ch1)
ch1 <- as.data.frame(ch1)
colnames(ch1) <- c("valores", "tipo")
rownames(ch1) <- 1: nrow(ch1)
regresion <- lm(valores ~ tipo, data = ch1)
summary(regresion)

print(ch1)

png("rlch1.png")
plot(ch1$tipo, ch1$valores, xlab = "Tipo de selecci\u{f3}n", ylab = "Valor", xaxt = "n")
axis(1, at=1:2, lab = c("Natural", "Artificial"))
abline(regresion)
graphics.off()
