mydata = read.csv("results.csv")
png("Paralelizar.png")
plot(log(mydata$k[mydata$cores == 1], 10), log(mydata$time[mydata$cores == 1]), xaxt="n", type = "l", xlab = "log(k)", ylab = "log(t)")
lines(log(mydata$k[mydata$cores == 2], 10), log(mydata$time[mydata$cores == 2]), col = "blue")
axis(1, at=3:6, lab = c("10^3", "10^4", "10^5", "10^6"))
legend("bottomright", c("1", "2"), cex=0.8, col=c("black", "blue"), lwd = 2, title = "Procesadores")
graphics.off()

cor(mydata)
regresion <- lm(times ~ k, data = mydata)
summary(regresion)

png("regresion.png")
plot(mydata$k[mydata$cores == 1], mydata$times[mydata$cores == 1], xlab = "p, k = 10 ^ p", ylab = "Tiempo(s)", col = "red", pch = 20, xaxt = "n")
points(mydata$k[mydata$cores == 2], mydata$times[mydata$cores == 2], col = "blue", pch = 23)
abline(regresion)
axis(1, at=c(1000, 10000, 100000, 1000000), lab = c("3", "4", "5", "6"))
legend("bottomright", c("Regresi\u{f3}n lineal", "1 procesador", "2 procesadores"), cex=0.8, col=c("black", "red", "blue"), pch = c(1, 20, 23))
graphics.off()
